### PR TITLE
XWIKI-23413: Separators in navigation tree dropdown

### PR DESCRIPTION
**Pull request by Sereza7**
# Jira URL

https://jira.xwiki.org/browse/XWIKI-23413

# Changes

## Description

* Updated the variable used in the LESS style block
* Changed the calculation back to what it was in LESS. The "new" way did not work on 16.10.X because some changes did not get backported (probably ones related to CSS variables :) ).

## Clarifications

* There's a compilation error because I added a CSS variable use in a LESS compiled file. The Vue style blocks are native CSS in 17.X. I didn't notice back then that using a CSS variable on a 16.10 backport is wrong anyways. But here it makes the whole style compilation fail so it's very bad.

# Screenshots & Video

I built the Livedata webjar and used it on my locale instance:
Screenshot from 2025-08-25 14-21-30

On the screenshot, we can see that unlike the 16.10.X tests (and what I got when starting my fresh 16.10.10-SNAPSHOT instance), the livedata has appropriate styles.

# Executed Tests

I built the changes successfully with `mvn clean install -f xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-webjar -Pquality`
then tested with ` mvn clean install -f xwiki-platform-core/xwiki-platform-livedata/xwiki-platform-livedata-test/xwiki-platform-livedata-test-docker/ -Dit.test="LiveDataIT#livedataLivetableTableLayout"`. The test passed. Before the changes, I could reproduce the fail found on CI.

# Expected merging strategy

* Prefers squash: Yes 
* Backport on branches:
  * None, apply only on 16.10.X

/!\ On merge, the commit message might use the wrong ticket reference, since my commits on the branch from which I'm proposing the PR have wrong descriptions.

### CODE REVIEW

**Comment by Sereza7** [comment]
For reference @manuelleduc 
Final state of the PR:
image

Here is what it looked like in the dropdown after only the first commit:
image

It's not as bad as before (LESS compilation doesn't fail), but there was still something quite wrong with the updated component :)
